config/routes.rb
Rails.application.routes.draw do
  get 'employees/about'
  get 'employees/contact'
  get 'employees/login'

  #post 'fares' => 'fares#index'
   post 'fares' => 'fares#index'
   post "/employees/login" => "employees#login_employee"

  resources :fares
  resources :trips
  resources :employees
  resources :trip_data
  resources :fare_data
  root 'employees#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:recordid, :vendorid, :pickup_datetime, :dropoff_datetime, :passenger_count, :trip_distance, :store_and_fwd_flag)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recordid %>
    <%= form.number_field :recordid, id: :trip_recordid %>
  </div>

  <div class="field">
    <%= form.label :vendorid %>
    <%= form.number_field :vendorid, id: :trip_vendorid %>
  </div>

  <div class="field">
    <%= form.label :pickup_datetime %>
    <%= form.datetime_select :pickup_datetime, id: :trip_pickup_datetime %>
  </div>

  <div class="field">
    <%= form.label :dropoff_datetime %>
    <%= form.datetime_select :dropoff_datetime, id: :trip_dropoff_datetime %>
  </div>

  <div class="field">
    <%= form.label :passenger_count %>
    <%= form.number_field :passenger_count, id: :trip_passenger_count %>
  </div>

  <div class="field">
    <%= form.label :trip_distance %>
    <%= form.text_field :trip_distance, id: :trip_trip_distance %>
  </div>

  <div class="field">
    <%= form.label :store_and_fwd_flag %>
    <%= form.text_field :store_and_fwd_flag, id: :trip_store_and_fwd_flag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>

<table>
  <thead>
    <tr>
      <th>Recordid</th>
      <th>Vendorid</th>
      <th>Pickup datetime</th>
      <th>Dropoff datetime</th>
      <th>Passenger count</th>
      <th>Trip distance</th>
      <th>Store and fwd flag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.recordid %></td>
        <td><%= trip.vendorid %></td>
        <td><%= trip.pickup_datetime %></td>
        <td><%= trip.dropoff_datetime %></td>
        <td><%= trip.passenger_count %></td>
        <td><%= trip.trip_distance %></td>
        <td><%= trip.store_and_fwd_flag %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recordid:</strong>
  <%= @trip.recordid %>
</p>

<p>
  <strong>Vendorid:</strong>
  <%= @trip.vendorid %>
</p>

<p>
  <strong>Pickup datetime:</strong>
  <%= @trip.pickup_datetime %>
</p>

<p>
  <strong>Dropoff datetime:</strong>
  <%= @trip.dropoff_datetime %>
</p>

<p>
  <strong>Passenger count:</strong>
  <%= @trip.passenger_count %>
</p>

<p>
  <strong>Trip distance:</strong>
  <%= @trip.trip_distance %>
</p>

<p>
  <strong>Store and fwd flag:</strong>
  <%= @trip.store_and_fwd_flag %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>