config/routes.rb
Rails.application.routes.draw do
  get 'employees/about'
  get 'employees/contact'
  get 'employees/login'

  #post 'fares' => 'fares#index'
   post 'fares' => 'fares#index'
   post "/employees/login" => "employees#login_employee"

  resources :fares
  resources :trips
  resources :employees
  resources :trip_data
  resources :fare_data
  root 'employees#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  establish_connection(:development)

  def self.checkID(empID)
    puts self.find_by_sql(["SELECT empid , first_name from Employee WHERE EMPID = ?", empID])
  end

  def self.create_user(first_name, last_name)
    self.find_by_sql("INSERT INTO Employee VALUES")
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find[params[:id]]
  end

  #only check whether employee exists in employee table or not.
  def login
    puts "*********************** LOGIN in EMPLOYEE ***************************"
    @employees = Employee.new
  end

  def login_employee
        puts "********************** LOGIN_PARAMS "+" **********************"

    puts "********************* LOGIN_EMPLOYEE in EMPLOYEE ***********************"
    @employee_id = params[:empid]
    @username = params[:name]
    @pass = params[:password]
    conn = OCI8.new('sanjana', 'Srvrtvk83!', 'oracle.cise.ufl.edu/orcl')
    cursor = conn.parse("select * from employee where empid="+@employee_id)

  #  puts "********************** Found the "+login_params+" **********************"
    cursor.exec

    @employee = cursor.fetch_hash
     # if @employee == 'NIL'
     #   render :js => "alert('Invalid Username or Password')"
     # end
    # puts @employee
    # puts "NAME YAHA AANA CHAHIE"
    # puts @employee["EMPID"]
    # puts @employee_id
    # puts @employee["USER_NAME"]
    # puts @username
    # puts @employee["EMP_PASSWORD"]
    # puts @pass

if @employee

    if @employee["USER_NAME"] == @username && @employee["EMP_PASSWORD"] == @pass
   # puts "********************** Found the "+@employee.first_name+" **********************"
      redirect_to employees_contact_path
      #format.html { redirect_to @employee, notice: 'You have successfully logged in.' }
     # format.json { render :show, status: :created, location: @employee }
    else
      render :js => "alert('Invalid Username or Password')"
      #flash.now[:danger] = 'Invalid email/password combination or you are not a user yet.'
    end

  else
       render :js => "alert('Id does not exists')"
  end

    conn.logoff
  end



  # GET /employees/NEW
  def new
    puts "********************* NEW in EMPLOYEE ************************"
    @employee = Employee.new
  end

  # POST /employees
  # POST /employees.json
  def create
    puts "********************* CREATE in EMPLOYEE ************************"
    @employee = Employee.new(register_params)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /employees/1/edit
  def edit
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:employee).permit(:first_name, :last_name, :email, :contact, :user_name, :emp_password)
    end

    def login_params
      params.require(:employee).permit(:user_name, :empid, :emp_password)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>


  <div class="field">
    <%= form.label :'first name' %>
    <%= form.text_field :first_name, id: :first_name %>

    <%= form.label :'last name' %>
    <%= form.text_field :last_name, id: :last_name %>

    <%= form.label :email %>
    <%= form.text_field :email, id: :employee_email %>

    <%= form.label :contact %>
    <%= form.text_field :contact, id: :employee_contact %>

    <%= form.label :'user name' %>
    <%= form.text_field :name, id: :employee_username %>


    <%= form.label :password %>
    <%= form.password_field :password, id: :password_field_tag %>
  </div>

  <div class="actions" >
    <%= form.submit "Register" %>
  </div>


<% end %>

app/views/employees/_formA.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :'first name' %>
    <%= form.text_field :first_name, id: :first_name %>
  </div>

<div class="field">
    <%= form.label :'last name' %>
    <%= form.text_field :last_name, id: :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :employee_email %>
  </div>

<div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact, id: :employee_contact %>
  </div>

<div class="field">
    <%= form.label :'user name' %>
    <%= form.text_field :user_name, id: :employee_username %>
  </div>

<div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :password_field_tag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/_formEL.html.erb
<%= form_with(model: employee, local: true) do |form| %>
<div class="field">
    <%= form.label :'Employee ID:' %>
    <%= form.text_field :empid, id: :empid %>



    <%= form.label :'user name' %>
    <%= form.text_field :name, id: :employee_username %>



    <%= form.label :password %>
    <%= form.password_field :password, id: :password_field_tag %>
  </div>

  <div class="actions">
    <%= form.submit "Log In"%>
  </div>
<% end %>

app/views/employees/about.html.erb
<html>
  <% provide(:title, "About") %>
  <head>
    <%= render 'layouts/navigationBar'%>
	</head>
  <body>
    <div class="container">
      <div class="centered">
        <h1>About Us:<h1>
      </div>
      <div class="row">
        <div style="width: 30%; margin: 25px auto ">

        </div>
      </div>
    </div>



	</body>
</html>

app/views/employees/contact.html.erb
<html>
	<% provide(:title, "Contact") %>
	<head>
        <%= render 'layouts/navigationBar'%>
	</head>
	<body>
		<div class="container">
      		<div class="centered">
	        	<h1>Contact Us:<h1>
		    </div>
		    <div class="row">
		        <div style="width: 30%; margin: 25px auto ">
		       
		        </div>
	      </div>
	    </div>
	</body>
</html>

app/views/employees/edit.html.erb
<% provide(:title, "Manage Account") %>

<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<html>
  <p id="notice"><%= notice %></p>
  <head>
    <%= render 'layouts/navigationBar'%>
  </head>

  <style>

  h1{
    padding-top: 500px;
    font-size: 70px;
  }

  </style>

  <body>
    <div class="container">
      <div class="centered">
        <h1>Welcome to Yellow Cab Services</h1>
      </div>
    </div>
  </body>
</html>

app/views/employees/login.html.erb
<html>
	<% provide(:title, "Login") %>
	<head>
	    <%= render 'layouts/navigationBar'%>
	</head>

	<style>

	.top{
		padding-top: 50px;
	}

	</style>

	<body>



		<div class="container-fluid">

		        <h1 class="top"></h1>


		            <%= render 'formEL', employee: @employee %>
		           

		</div>
	</body>
</html>

app/views/employees/new.html.erb
<html>

	<head>
      <% provide(:title, "Register") %>
      <%= render 'layouts/navigationBar'%>
	</head>

	<style>

	.top{
	  padding-top: 50px;
	}

	</style>

<body>


<div class="container-fluid">

				<h1 class="top">Registration</h1>
          <%= render 'form', employee: @employee %>
				

</div>
	</body>
</html>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |