config/routes.rb
Rails.application.routes.draw do
  get 'employees/about'
  get 'employees/contact'
  get 'employees/login'

  #post 'fares' => 'fares#index'
   post 'fares' => 'fares#index'
   post "/employees/login" => "employees#login_employee"

  resources :fares
  resources :trips
  resources :employees
  resources :trip_data
  resources :fare_data
  root 'employees#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fare.rb
class Fare < ApplicationRecord

end

app/controllers/fares_controller.rb
class FaresController < ApplicationController
  before_action :set_fare, only: [:show, :edit, :update, :destroy]

  # GET /fares
  # GET /fares.json
  def index
    @fareval = params[:month]
    if @fareval then
      puts "Value of selected month is " + @fareval
      conn = OCI8.new('sanjana', 'Srvrtvk83!', 'oracle.cise.ufl.edu/orcl')
      #@fares = []
      #query = "SELECT * FROM TRIP_DATA WHERE ROWNUM < 10"
      query = "SELECT TRIP_DISTANCE as \"Trip Distance\", FARE_DATA.TOLLS_AMOUNT as \"Total tolls\" FROM TRIP_DATA, FARE_DATA WHERE TRIP_DATA.RECORDID = FARE_DATA.RECORDID AND TRIP_DATA.RECORDID = (SELECT RECORDID FROM FARE_DATA WHERE TOLLS_AMOUNT = (SELECT MAX(TOLLS_AMOUNT) FROM FARE_DATA))"
      cursor = conn.parse(query)
      cursor.exec
      #while r = cursor.fetch_hash
    #    @fares << r
    #  end
    #  puts @fares
      conn.logoff
      format.html { render action: "index" }
    else
      conn = OCI8.new('sanjana', 'Srvrtvk83!', 'oracle.cise.ufl.edu/orcl')
      @fares = []
      query = "SELECT * FROM TRIP_DATA WHERE ROWNUM < 10"
      #query = "SELECT TRIP_DISTANCE as \"Trip Distance\", FARE_DATA.TOLLS_AMOUNT as \"Total tolls\" FROM TRIP_DATA, FARE_DATA WHERE TRIP_DATA.RECORDID = FARE_DATA.RECORDID AND TRIP_DATA.RECORDID = (SELECT RECORDID FROM FARE_DATA WHERE TOLLS_AMOUNT = (SELECT MAX(TOLLS_AMOUNT) FROM FARE_DATA))"
      #query = "SELECT TO_CHAR(PICKUP_DATETIME, 'mm') AS \"Month\", COUNT(RECORDID) AS \"Passenger Count\" FROM TRIP_DATA WHERE TO_CHAR(PICKUP_DATETIME, 'YYYY')=2015 GROUP BY TO_CHAR(PICKUP_DATETIME, 'mm') ORDER BY TO_CHAR(PICKUP_DATETIME, 'mm') DESC"
      #query = "SELECT * FROM TRIP_DATA WHERE ROWNUM < 50"
      cursor = conn.parse(query)
      cursor.exec
      while r = cursor.fetch_hash
        @fares << r
      end
      puts @fares
      conn.logoff
    end
  end

  def onMonthSelect
  end

  # GET /fares/new
  def new

  end

  # GET /fares/1/edit
  def edit
  end

  # POST /fares
  # POST /fares.json
  def create
    @fare = Fare.new(fare_params)

    respond_to do |format|
      if @fare.save
        format.html { redirect_to @fare, notice: 'Fare was successfully created.' }
        format.json { render :show, status: :created, location: @fare }
      else
        format.html { render :new }
        format.json { render json: @fare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fares/1
  # PATCH/PUT /fares/1.json
  def update
    respond_to do |format|
      if @fare.update(fare_params)
        format.html { redirect_to @fare, notice: 'Fare was successfully updated.' }
        format.json { render :show, status: :ok, location: @fare }
      else
        format.html { render :edit }
        format.json { render json: @fare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fares/1
  # DELETE /fares/1.json
  def destroy
    @fare.destroy
    respond_to do |format|
      format.html { redirect_to fares_url, notice: 'Fare was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fare
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fare_params
      #params.require(:fare).permit(:recordid, :tip_amount, :extra, :mta_tax, :ratecodeid, :tolls_amount, :total_amount, :fare_amount, :improvement_surcharge, :payment_type)
    end
end

app/helpers/fares_helper.rb
module FaresHelper
end

app/views/fares/_form.html.erb
<%= form_with(model: fare, local: true) do |form| %>
  <% if fare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fare.errors.count, "error") %> prohibited this fare from being saved:</h2>

      <ul>
      <% fare.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recordid %>
    <%= form.number_field :recordid, id: :fare_recordid %>
  </div>

  <div class="field">
    <%= form.label :tip_amount %>
    <%= form.text_field :tip_amount, id: :fare_tip_amount %>
  </div>

  <div class="field">
    <%= form.label :extra %>
    <%= form.text_field :extra, id: :fare_extra %>
  </div>

  <div class="field">
    <%= form.label :mta_tax %>
    <%= form.text_field :mta_tax, id: :fare_mta_tax %>
  </div>

  <div class="field">
    <%= form.label :ratecodeid %>
    <%= form.number_field :ratecodeid, id: :fare_ratecodeid %>
  </div>

  <div class="field">
    <%= form.label :tolls_amount %>
    <%= form.text_field :tolls_amount, id: :fare_tolls_amount %>
  </div>

  <div class="field">
    <%= form.label :total_amount %>
    <%= form.text_field :total_amount, id: :fare_total_amount %>
  </div>

  <div class="field">
    <%= form.label :fare_amount %>
    <%= form.text_field :fare_amount, id: :fare_fare_amount %>
  </div>

  <div class="field">
    <%= form.label :improvement_surcharge %>
    <%= form.text_field :improvement_surcharge, id: :fare_improvement_surcharge %>
  </div>

  <div class="field">
    <%= form.label :payment_type %>
    <%= form.number_field :payment_type, id: :fare_payment_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fares/index.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard</title>

    <!-- Cascading Style Sheets -->
    <link href="/app/assets/stylesheets/bootstrap.min.css" rel="stylesheet">
    <link href="/app/assets/stylesheets/analytics.css" rel="stylesheet">
</head>


<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link">Trends</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href=<%=fares_path %>>Analytics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link">Manage Account</a>
            </li>
            <li class="nav-item">
                <a class="nav-link">Log Out</a>
            </li>
          </ul>
      </div>
    </nav>
    <div class="container-fluid divider"></div>

    <div class="container-fluid py-4"></div>
    <div class="container-fluid">
       <!-- <div class="row"> -->
            <div class="container col-lg-10 col-md-12 offset-lg-1 offset-md-0">
            <!--Grid row-->
            <div class="row">

            <!--Grid column-->
                <div class="col-lg-3 col-md-12">
                <!--Name-->
                    <%= form_with url: fares_path do |f| %>
                        <%= f.select :month, { "January" => "01", "February" => "02", "March" => "03", "April" => "04", "May" => "05", "June" => "06", "July" => "07", "August" => "08", "September" => "09", "October" => "10", "November" => "11", "December" => "12" }, { include_blank: 'Please choose' } %>
                        <%= button_to "Get Passenger Count", action: "index" %>
                    <% end %>
                    <!--<select id="category_id" name="category[id]" class="custom-select py-0 table-shadow">
                        <option value="" disabled selected>Select Month</option>
                        <option value="01">January</option>
                        <option value="02">February</option>
                        <option value="03">March</option>
                        <option value="04">April</option>
                        <option value="05">May</option>
                        <option value="06">June</option>
                        <option value="07">July</option>
                        <option value="08">August</option>
                        <option value="09">September</option>
                        <option value="10">October</option>
                        <option value="11">November</option>
                        <option value="12">December</option>
                    </select> -->

                </div>
                <!--Grid column-->

            <!--Grid column-->
                <div class="col-lg-3 col-md-6">

            <!--Blue select-->
                    <select class="custom-select py-0 table-shadow">
                        <option value="" disabled selected>Select Year</option>
                        <option value="2015">2015</option>
                        <option value="2016">2016</option>
                        <option value="2017">2017</option>
                    </select>
            <!--/Blue select-->

                </div>
        <!--Grid column-->

        <!--Grid column-->
                <div class="col-lg-3 col-md-6">

            <!--Blue select-->
                    <select class="custom-select py-0 table-shadow">
                        <option value="" disabled selected>Optional Filter (TBD)</option>
                        <option value="1">Contacts in no segments <span> (100)</span></option>
                        <option value="1">Segment 1 <span> (2000)</span></option>
                        <option value="2">Segment 2 <span> (1000)</span></option>
                        <option value="3">Segment 3 <span> (4000)</span></option>
                    </select>
            <!--/Blue select-->
                </div>
        <!--Grid column-->
                <div class="col-lg-3 col-md-6 table-shadow">
                    <%= button_to "Get Passenger Count", action: "index" %>
                    <!--<button type="button" class="btn btn-outline-info table-shadow" data-toggle="tooltip" data-placement="bottom" title="Get monthly count of passengers for the given year" id="viewAnalytics">Get Passenger Count</button>-->
                </div>
        <!--Grid column-->
            </div>
            <!--Grid row-->
            <!--Top Table UI-->
            </br>
                <div class="table-responsive">
                        <table class="table table-responsive-md table-shadow" id="analytics-table">
                            <thead class="thead-light">
                                <tr>
                                    <% @fares.first.keys.each do |key| %>
                                    <th><%= key %></th>
                                    <% end %>
                                </tr>
                            </thead>
                            <tbody>
                                <% @fares.each do |fare| %>
                                <tr>
                                    <% fare.each do |key, value| %>
                                    <td><%= value %></td>
                                    <% end %>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                </div>

            <div class="d-flex justify-content-between">
            <!--Name-->
                        <div class="col-lg-3 col-md-4">
                            <select class="custom-select py-0 table-shadow">
                                <option value="" disabled >Rows number</option>
                                <option value="1" selected>10 rows</option>
                                <option value="2">20 rows</option>
                                <option value="3">30 rows</option>
                            </select>
                        </div>
            <!--Pagination -->
                        <div class="col-md-4">
                            <ul class="pagination pagination-circle pg-blue mb-0 table-shadow">
                    <!--First-->
                                <li class="page-item disabled"><a class="page-link">First</a></li>
                    <!--Arrow left-->
                                <li class="page-item disabled">
                                    <a class="page-link" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                    <!--Numbers-->
                                <li class="page-item active"><a class="page-link">1</a></li>
                                <li class="page-item"><a class="page-link">2</a></li>
                                <li class="page-item"><a class="page-link">3</a></li>

                    <!--Arrow right-->
                                <li class="page-item">
                                    <a class="page-link" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </li>
                    <!--First-->
                                <li class="page-item"><a class="page-link">Last</a></li>
                            </ul>
                        </div>
                        <!--/Pagination -->

                    </div>
        </div>
    <!-- </div> -->
<br>

    <script src="js/jquery-3.3.1.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/app/assets/javascripts/popper.min.js"></script>
    <script src="/app/assets/javascripts/bootstrap.min.js"></script>
</body>
</html>

app/views/fares/show.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard</title>

    <!-- Cascading Style Sheets -->
    <link href="/app/assets/stylesheets/bootstrap.min.css" rel="stylesheet">
    <link href="/app/assets/stylesheets/analytics.css" rel="stylesheet">
</head>


<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href=<%=fares_path %>>Analytics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=<%=employees_path %>>Log Out</a>
            </li>
          </ul>
      </div>
    </nav>
    <div class="container-fluid divider"></div>

    <div class="container-fluid py-4"></div>
    <div class="container-fluid">
       <!-- <div class="row"> -->
            <div class="row">
                <div class="col-lg-3 col-md-6">
                        <%= link_to 'Back', fares_path, {:class => 'btn btn-outline-info table-shadow', :method => :get } %>
                </div>
            </div>
            <!--Grid row-->
            <!--Top Table UI-->
            </br>
                <div class="table-responsive">
                    <% if @fares then %>
                        <table id="tblanalytics" class="table table-responsive-md table-shadow" id="analytics-table">
                            <thead class="thead-light">
                                <tr>
                                    <% @fares.first.keys.each do |key| %>
                                    <th><%= key %></th>
                                    <% end %>
                                </tr>
                            </thead>
                            <tbody>
                                <% @fares.each do |fare| %>
                                <tr>
                                    <% fare.each do |key, value| %>
                                    <td><%= value %></td>
                                    <% end %>
                                </tr>
                                <% end %>
                            </tbody>
                        </table>
                    <% end %>
                </div>
        </div>
    <!-- </div> -->
<br>

    <script src="js/jquery-3.3.1.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/app/assets/javascripts/popper.min.js"></script>
    <script src="/app/assets/javascripts/bootstrap.min.js"></script>
</body>
</html>